//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace key_pocFinal.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int ID { get; set; }
        public int ProductSubCategoryID { get; set; }
        public int ProductDescID { get; set; }
        public int ProductTecSpecID { get; set; }
        public string ProductImage { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
    
        public virtual tblSubCategory tblSubCategory { get; set; }
        public virtual tblProductDescription tblProductDescription { get; set; }
        public virtual tblProductType tblProductType { get; set; }
        public virtual tblTechnicalSpec tblTechnicalSpec { get; set; }
    }
}
