//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace key_pocFinal.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTechnicalSpec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTechnicalSpec()
        {
            this.tblProducts = new HashSet<tblProduct>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AirFlow { get; set; }
        public Nullable<double> MinPow { get; set; }
        public Nullable<double> MaxPow { get; set; }
        public Nullable<double> MinOV { get; set; }
        public Nullable<int> MinRPM { get; set; }
        public Nullable<int> MaxRPM { get; set; }
        public Nullable<int> NumberFanSpeed { get; set; }
        public Nullable<double> dB { get; set; }
        public Nullable<double> FanSweepDiameter { get; set; }
        public Nullable<double> MinHeight { get; set; }
        public Nullable<double> MaxHeight { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> MaxOV { get; set; }
        public Nullable<int> Min_Pumping_Speed { get; set; }
        public Nullable<int> Max_Pumping_Speed { get; set; }
        public string Hose { get; set; }
        public Nullable<double> dustCapcity { get; set; }
        public Nullable<int> multipleToastSetting { get; set; }
        public Nullable<double> cordLength { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduct> tblProducts { get; set; }
    }
}
