//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace key_pocFinal.DBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTSFilter
    {
        public int ID { get; set; }
        public int SubCategoryID { get; set; }
        public string PropertyName { get; set; }
        public int Min { get; set; }
        public int Max { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tblSubCategory tblSubCategory { get; set; }
    }
}
